### ISSUE TITLE
Shia LaBeouf

### ISSUE THREAD

**Issue by Davnik** [HeavensGate/Eternal#101]
Change the message received from bear traps to "Your leg! Aahhh! It's caught in a bear trap!"

**Comment by Jacquar** [comment]
Don't.

**Comment by woothie** [comment]
Normal Tuesday Night for Shia LeBeouf

**Comment by Davnik** [comment]
Added "Audio" and "invalid" tags, because you would understandably be screaming a lot, and promptly become an invalid

**Comment by woothie** [comment]
God damn it Davnik.

**Comment by Davnik** [comment]
If your leg were caught in a bear trap, you'd probably think this was high priority. If you were a member of the staff, you might consider this low priority.

**Comment by Davnik** [comment]
But there's nothing uncertain about how bad that would hurt.
