### ISSUE TITLE
Adminbot Inconsistencies 

### ISSUE THREAD

**Issue by CitationNeeded** [HeavensGate/Eternal#102]
Adminbot will autoadd player notes for some bans while totally ignoring others. It's a minor problem but it does leave some issues with our organization.

**Comment by Davnik** [comment]
Adminbot adds notes on Player Panel > Jobban, but not on Player Panel > Ban. Please have adminbot make notes of both.

**Comment by Davnik** [comment]
This seems to be resolved; reopen if not.
