### ISSUE TITLE
Cargo Shutters

### ISSUE THREAD

**Issue by Davnik** [HeavensGate/Eternal#114]
It has been recommended that cargo get shutters over the Delivery Office and Cargo Lobby windows, e.g. those hall-adjacent. I imagine the QM will want a button on his side table, and there should also be one at the Delivery Office desk. Jakk approves; any dissent?

**Comment by staticcharged** [comment]
That's a great idea actually.

**Comment by Jacquar** [comment]
Go further, add a pair of shutter doors in place of a wall in the cargo office, for large deliveries to hypothetically be brought through. Let the entire cargo bay open onto the corridor. 

Defy walls!

Become independent!

**Comment by staticcharged** [comment]
are we talking the same type of shutter doors that close off the kitchen counter to the hallway? it would be like a big garage door right?

**Comment by CitationNeeded** [comment]
I hate shutters. Doing it now, will update with screenshot.

**Comment by killer99603** [comment]
Done
