### ISSUE TITLE
Trawl older repositories

### ISSUE THREAD

**Issue by Jacquar** [HeavensGate/Eternal#118]
@Davnik Please trawl the other repo/s under HeavensGate and pull any pertinent issues over to this one, when you have time.

@woothie : Do we need the older ones?

**Comment by woothie** [comment]
There is none, except for mapping content. All code is merged, icons are outside of the old Eternal repo, but are indeed not implemented yet. They include: Para's work before ???, including his PDAs - Finriv's AI things, flooring and whatnot. Basically everything we've made in terms of sprites.

**Comment by Jacquar** [comment]
Yes. That.

**Comment by staticcharged** [comment]
are we using paras pda sprites?

**Comment by woothie** [comment]
No, we are not. I do still have them on my google drive though, and I'd like a discussion on whenever we're using them or not, with everyone attending. It's a rather... omni-affecting change, and I'd like as many inputs as we can.
