### ISSUE TITLE
Flare Cabinets

### ISSUE THREAD

**Issue by Davnik** [HeavensGate/Eternal#129]
Implement cabinets in all departments and public places which contain flares and blue fleshlights. Sprites are in development by Jakk and Fin, their contents will need to be implemented by coding (using fire/oxygen/pill cabinet code?), then mapping will need to find places for them.

**Comment by CitationNeeded** [comment]
http://i.gyazo.com/f2843739c46d77565181d9fb726f644c.png

**Comment by Davnik** [comment]
wonk

**Comment by Mewchild** [comment]
I'll work on this

**Comment by Mewchild** [comment]
This can be closed.

**Comment by woothie** [comment]
Mark a PR or commit with "Fixes #129" and it will be.

**Comment by Mewchild** [comment]
I did, nerd. "Closes: #129"

**Comment by woothie** [comment]
Fixes* ya doof
