### ISSUE TITLE
Forum-suggested APC/Map Bugs

### ISSUE THREAD

**Issue by Davnik** [HeavensGate/Eternal#147]
http://www.heavensgatestation.com/post/map-bugs-and-power-net-issues-7408975?pid=1287207839
Please review this page and fix the associated bugs:
* DroneFab Exosuit Fab has no south-facing access to dispense parts
* APC's and the mentioned Civilian East Breaker Room may need another look-over.
* The Library, and possibly some other places, have duplicate APC's, which can lead to problems.

**Comment by CitationNeeded** [comment]
Fixed. Please close ASAP.
