### ISSUE TITLE
Vox Heads

### ISSUE THREAD

**Issue by Davnik** [HeavensGate/Eternal#156]
We need to decide between ourselves how we want Vox to be allowed on-station. We have generally agreed that admins should hand it out to anyone trusted mid-round, but a loophole exists that allows them at roundstart, which means they can join as heads... we want to resolve some of this with at least a temporary fix while we decide our overall stance on a race that has become inundated elsewhere with false impressions. 

Standing suggestions/possibilities are to whitelist Vox from Captain, whitelist Vox from all Heads, blacklist Vox as it is misused, remove Vox from roundstart, or sod the whole issue and allow Vox as a fully-supported playable race and handle problem children that roleplay it ignorantly on a case-by-case basis.

**Comment by Davnik** [comment]
This topic will drop from URGENT to high priority when voxes can't be captains at roundstart, because this causes RP disturbances. If it's closed at that time... no biggie.

**Comment by Davnik** [comment]
Given the state of coders... let's just say voxes as captains get a tap on the shoulder.

**Comment by Davnik** [comment]
git, right?

**Comment by Mewchild** [comment]
@Davnik Status on this?

**Comment by staticcharged** [comment]
Vox should absolutely not be allowed to assume Head Roles. That defies all logic.

**Comment by Davnik** [comment]
While there are some justifications for vox heads in the right mindset/mentality, we're moving Vox back to their rightful place as rare antags. This is a current non-issue. Current.
