### ISSUE TITLE
Jobban Panel "Antagonist"

### ISSUE THREAD

**Issue by Davnik** [HeavensGate/Eternal#160]
The "Antagonist" link on the Jobban panel only bans from Traitor, as opposed to "all antags."

**Comment by sshado** [comment]
The 'Antagonist Roles' job ban works correctly as far as the code is concerned. What is happening is it displays 'You are banned from [Syndicate]' rather than 'You are banned from [Antagonists]'. Syndicate being all antagonist roles.

I will make a code change that renames 'Syndicate' to 'Antagonists' so that there is no confusion.

**Comment by sshado** [comment]
/code/modules/admin/topic.dm

ORIGINAL:

//Antagonist (Orange)
		var/isbanned_dept = jobban_isbanned(M, "Antagonists")
		jobs += "<table cellpadding='1' cellspacing='0' width='100%'>"
		jobs += "<tr bgcolor='ffeeaa'><th colspan='10'><a href='?src=\ref[src];jobban3=Syndicate;jobban4=\ref[M]'>Antagonist Positions</a></th></tr><tr align='center'>"

UPDATED:

//Antagonist (Orange)
		var/isbanned_dept = jobban_isbanned(M, "Antagonists")
		jobs += "<table cellpadding='1' cellspacing='0' width='100%'>"
		jobs += "<tr bgcolor='ffeeaa'><th colspan='10'><a href='?src=\ref[src];jobban3=Syndicate;jobban4=\ref[M]'>Antagonist Positions</a></th></tr><tr align='center'>"


-------------------------------------------------

/game/gamemodes/game_mode.dm

ORIGINAL:

	// Assemble a list of active players without jobbans.
	for(var/mob/new_player/player in player_list)
		if( player.client && player.ready )
			if(!jobban_isbanned(player, "Syndicate") && !jobban_isbanned(player, roletext))
				players += player
UPDATED:

	// Assemble a list of active players without jobbans.
	for(var/mob/new_player/player in player_list)
		if( player.client && player.ready )
			if(!jobban_isbanned(player, "Antagonists") && !jobban_isbanned(player, roletext))
				players += player

**Comment by Mewchild** [comment]
Why was this never implemented?

**Comment by staticcharged** [comment]
Bump

**Comment by Davnik** [comment]
Never seen. : p

**Comment by killer99603** [comment]
I'm going to start trying to work on the small code issues. This is now done and I'll have it pushed with (hopefully) some more small stuff.
