### ISSUE TITLE
Automated Shuttle Calls Every Hour

### ISSUE THREAD

**Issue by Davnik** [HeavensGate/Eternal#171]
A player has recommended returning the shuttle call to 2/3/4/5 instead of 2/4/6/8, in the interest of slow rounds. A crew majority vote feels the same way.

**Comment by Mewchild** [comment]
@woothie @aztectornado

**Comment by Davnik** [comment]
I've had this discussion countless times throughout the months, and I think we can say the majority opinion is 2/3/4/5... I think I can also do this from config myself.
