### ISSUE TITLE
Split LOOC and OOC

### ISSUE THREAD

**Issue by Davnik** [HeavensGate/Eternal#173]
Pretty much the title. Muting OOC mutes LOOC as well. There should be a separate verb and they should function independently. Also, if it isn't a thing, individual players should be mutable from one or the other.

Adding the simple/easy label, as this should be a reeeelatively simple fix. Just a new verb, a deletion from an old verb, an addition to the new verb... and references. .,.

**Comment by woothie** [comment]
Fixed in #185
