### ISSUE TITLE
Phoner to Arizoner (Lobby Music)

### ISSUE THREAD

**Issue by Davnik** [HeavensGate/Eternal#176]
Finriv made the title. But tight.
Please get this onto the lobby music selection.
Request the .mp3 in Skype if you need it. Also that needs to be converted to .ogg. Because Audacity needs love too.

**Comment by woothie** [comment]
Or upload to dropbox and provide link? :[

**Comment by Davnik** [comment]
Dropbox link, .mp3, might need to convert to .ogg

https://www.dropbox.com/s/10qgq0vmqbvlz8b/Gorillaz%20-%20Phoner%20To%20Arizona.mp3?dl=0

**Comment by Davnik** [comment]
Two oppositions, closing for now
