### ISSUE TITLE
Singularity Engine

### ISSUE THREAD

**Issue by Davnik** [HeavensGate/Eternal#180]
While we are holding our breaths for the Supermatter to provide an alternative, we are still dealing with the daily problems of a faulty singularity engine. Many things need to be fixed and investigated and ensured reliable. I won't be able to list them all now, but it's very buggy. Chief concern at the moment: eventually (5 hours in) the Emitter SMES stops charging/outputting, and then containment fails.

**Comment by CitationNeeded** [comment]
99.99999% sure that this is fixed in my next update. If everything is fine after the update I'll close this.

**Comment by Mewchild** [comment]
The reason the SMES stops outputting is RNG based; It's died to the grid check event. After doing some testing, I've found that the grid check is area dependant on what it does (almost everything) and doesn't (AI Core) hit. The Engine room area needs to be added to the list of areas that AREN'T pinged, then the SMES won't be drained, containment won't fail and we can enable movement on the bastard again.

**Comment by Mewchild** [comment]
This has been done, and the issue can be closed.

**Comment by Davnik** [comment]
Hopefully no more singulo issues. I think it runs perfectly as intended at present, though... I don't know if we ever made it self_move. Nonetheless, can close this "early bugs" issue.
