### ISSUE TITLE
Latejoin in Space at Lobby

### ISSUE THREAD

**Issue by Davnik** [HeavensGate/Eternal#183]
Hunnewle joined as Newle, his IPC/Machine, and arrived at... the Lobby, in space. Instead of cryogenic storage. I personally believe this is because of the antiquated Cyborg Storage spawn point, which has been removed. Any characters with that latejoin spawn location need to select Cryogenic Storage.

If that is not the issue, i.e. if someone else has this problem, we'll push this up in priority.

Noted as both Code and Mapping, as it is either a misplaced possible spawn point, or a bugged reference in the code. The player may be able to resolve it through character creation screen though, making it neither.

**Comment by aztectornado** [comment]
This was an issue on UT sometimes too. I forget what caused it, but one day it mysteriously stopped happening

**Comment by Davnik** [comment]
This hasn't happened in a month. js.

**Comment by Davnik** [comment]
Tentatively assuming this doesn't happen.
