### ISSUE TITLE
Roundstart with no players ready

### ISSUE THREAD

**Issue by woothie** [HeavensGate/Eternal#22]
Just what it says on the box. The round starts based on number of players online (not ready, just online), while we want it to be based of number of players ready. This to circumvent empty rounds with no admins or players, new players join to an empty, powerless station. Also allow admins to override this, but start-now already does this persumably (but check it anyways). On that note, redo number of players required, assume a couple more players will latejoin as the round goes. Codenote: Each gamemode .dm handles required players, go check them. For numbers, ask Core, wait for Jakk/Dav/Static response or start discussion.

**Comment by woothie** [comment]
Connects to #33

**Comment by Mewchild** [comment]
I'll test this later, I don't believe it's still an issue

**Comment by Davnik** [comment]
The issue is, we have long, long, long, long rounds before anyone shows up. Like, 14:00 and nobody is here. Maybe we can add "10 minutes after nobody is controlling a mob, restart."
