### ISSUE TITLE
MechBay Air Issue

### ISSUE THREAD

**Issue by Mewchild** [HeavensGate/Eternal#235]
Mechbay and one other spot (can't find it now, will comment the location), have permanent minor air alarms, even on round start. Nothing in the vars looks to be off. Testing in server shows that the air mixture for the room starts slightly off (18% O2, instead of 20%). Not sure what causes this, but I'm looking into it.

//gently bristles at inability to label this properly

**Comment by Mewchild** [comment]
//gently bristles at inability to label this properly

**Comment by Davnik** [comment]
Woothie noted, as he was attempting to do the BS12 merge some months ago, that a few of the tiles default to... nitrogen air. Just nitrogen air. This, of course, immediately processes out into default air. Look into the bizarre tiles we chose to use for the mech charging ports, namely the green AI tiles - they originate from something foreign like the Derelict, so they might have an odd air type.

**Comment by Mewchild** [comment]
Got it. Looking into them now

**Comment by killer99603** [comment]
Green files tiles fixed. If we find the second room with the air alarm, repeat a similar process.
