### ISSUE TITLE
Release the Slimes

### ISSUE THREAD

**Issue by Davnik** [HeavensGate/Eternal#242]
The slime minigame is a classic favorite, but it's time for it to get a roleplaying workover, to repurpose Xenobio into the latest practically unused, overly specific roleplay room. 

Release the slimes. Put them in maintenance halls all over the station. If a scientist (xenobiologist) wants slimes to work with in the xenobio department, he'll have to get maintenance access somehow, and that will probably involve discussing plans and/or bribing, all good roleplay. And, this will make the shadows of maintenance inherently deceptively dangerous. we'll probably want to put fire extinguishers in various places throughout maintenance, even more than already exist.

Without the slimes, people will want to know what the room is used for now, if its minigame purpose is gone. We'll need to leave a clearly visible note in Xenobio, explaining that the room will now be used for researching alien species - implying that the room will be a quarantine for first contact, or other study and scientific research.

**Comment by Mewchild** [comment]
I'm not comfortable releasing the slimes until we have a code redo for them, to remove their innate aggro tendencies. They're nightmarish to fight as is, and need to be toned down before moving them out into the wild, I feel.

**Comment by Davnik** [comment]
They aggro when hungry! You need to understand them; they are gentle creatures! LISTEN TO ME! --John Steele, Xenobiologist (TERMINATED)

**Comment by Mewchild** [comment]
They're aggro when hungry, or in general to anyone who hasn't been marked as "Friend". Friends are marked by line of sight whilst they feed.

**Comment by Davnik** [comment]
But really... the intention is to add them as an inherent DANGER in maintenance, and if they get out and fuck people up... that's someone's fault. If you want to travel in maint, you need an extinguisher and/or pocket monkey. Free conflicts!

If code gives them a nerf/fix, it should simply lower the health level at which they go aggro, so that they are only liable to flip shit on a random stranger if they're minutes from death or attacked. This will be step one of the players learning the danger of the NSS Eternal, and the danger of failing to cooperate with aliens and run things by research. <3

Regardless, I'll push this to a code issue to make them "safe for maintenance."

**Comment by Mewchild** [comment]
The problem with fighting slimes is that fire extinguishers are incredibly imprecise. I've seen a slime take down four people in short order, all of them attempting to spray it. A good way to fix this would be to add a check; clicking a slime with the extinguisher not trigger a melee, if safety is off.  It instead sprays the extinguisher normally.

**Comment by Davnik** [comment]
Approved addition, and I'll still make sure the slime doesn't readily attack casuals.

**Comment by woothie** [comment]
Why was this closed? When doing this, please actually comment or tell people with push access why.  @staticcharged
