### ISSUE TITLE
Control The Slimes

### ISSUE THREAD

**Issue by Davnik** [HeavensGate/Eternal#244]
Since we're moving them into maintenance, slimes should not default to attacking any reachable [humanoid / player] unless they are minutes from death, or that [humanoid / player] has attacked them. This should include silicons, if necessary. Slimes should not call these individuals "friend" - that should follow the same rules. Slimes should continue to attack monkies, mice, and other animals indiscriminately.

Furthermore, clicking a slime with a fire extinguisher whose safeties are off should result in the slime being sprayed, despite the standard fire extinguisher mechanics. This should have a custom redtext saying [mob] has sprayed [slime]! and expend the water, applying the appropriate effects to the slime: a waterspot may appear on the slime's tile, and the slime will lose the appropriate amount of health. If the safety is on, the fire extinguisher will be used to melee the slime normally. If the extinguisher is empty, a separate message will alert the user, and the extinguisher will be used to melee the slime normally.

**Comment by Davnik** [comment]
This should be completed before, or shortly after (a docility mutation forced by researchers?) #242.

**Comment by Davnik** [comment]
It should be noted that this update will entirely be done because the crew does not have the patience or robustitude to deal with slimes in the proper fashion. For shame.

**Comment by Mewchild** [comment]
It should also be noted that fire extinguishers suck, and slimes are immune to damage.

**Comment by Davnik** [comment]
It is the esteemed gentleplayer's bwoink.

**Comment by Mewchild** [comment]
You're a gentle player's bwoink :I

**Comment by woothie** [comment]
Why was this closed? @staticcharged
