### ISSUE TITLE
Inf Plasma Cutters

### ISSUE THREAD

**Issue by Davnik** [HeavensGate/Eternal#256]
"I've noticed with the industrial hardsuit that if the middle mouse button is clicked on a conveyor belt with the plasma cutter module active, it will plop down a plasma cutter. I don't know if it happens to other hardsuits, but I know for sure it happens for that one."

This allows for the production of infinite plasma cutters... or, say, an epidemic of Cargonian uprisings.

**Comment by Davnik** [comment]
Honestly, this should be as simple as preventing the plasma cutter from being able to be set down, on anything, anywhere. It's an internal tool to the hardsuit, not something up your sleeve. When the hardsuit is removed, it should remove the plasma cutter from your hand.

**Comment by woothie** [comment]
As with many things SS13, it's not that simple. I've looked into it and I
need to dig into some documentation to find some references. Unfortunately
it's also 4AM and I have work tomorrow. So. When I get back from that, or
before, mayhaps.

**Comment by aztectornado** [comment]
Now prototyping a fix for this...

**Comment by aztectornado** [comment]
Found the fix on Bay. Wouldn't you know it's a single line?

**Comment by Davnik** [comment]
Oh boy.
