### ISSUE TITLE
Dispose Reagents Button

### ISSUE THREAD

**Issue by Davnik** [HeavensGate/Eternal#295]
Add a button to the Chemical Dispenser, Booze-o-Mat, and Soda Dispenser, which allows you to (safely) empty the current container, without pouring it on something or someone. People are getting tired of my fountain of accidental pacid. Barkeeps don't want to drink their "glass of... what?" every time. And so on.

**Comment by Puckaboo2** [comment]
mfw you keep drinking botched drinks, thinking nobody noticed a screw-up.

**Comment by Mewchild** [comment]
mfw it's still delicious

**Comment by Puckaboo2** [comment]
mfw you add extra uranium and ab+ blood

**Comment by Mewchild** [comment]
mfw it's _still_ delicious

**Comment by Puckaboo2** [comment]
mfw you get a pure drink

**Comment by Mewchild** [comment]
mfw when it somehow has something lacking

**Comment by Puckaboo2** [comment]
mfw chemist slips on spilled pacid and radium

**Comment by woothie** [comment]
mfw email notices go nuts over shenanigans in the comments of an issue

**Comment by Davnik** [comment]
>>comment left by email reply
flawless

**Comment by Davnik** [comment]
don't do two right carats or you get that

**Comment by Puckaboo2** [comment]
"The chem dispenser, Booze-O-Mat, soda dispenser and sleeper all need dispose fluids/reagents/chemicals/blood/etc buttons/functions which allow them to directly remove/delete/empty their containers' contents. Dialysis beakers are having to be splashed on the floor, their contents processed therein and the roleplay disturbed, and it's easy to botch the recipes for the other machines and need to subtly tweak the contents with machines you may or may not have access to." 

I had no clue Dav posted an issue on this, before. Apologies for requesting to bring it up, again.

**Comment by Davnik** [comment]
#198
duplicate tag, go!
