### ISSUE TITLE
Berry Juice,Tomato Juice, Poison & Blood

### ISSUE THREAD

**Issue by staticcharged** [HeavensGate/Eternal#304]
Recently it was pointed out that upon visible inspection you can tell Berry Juice from Poison Berry Juice, which seems pretty meta- and a tad eyebrow raising when compared to the fact that upon visible  inspection you cannot tell the difference between a glass of tomato juice and blood. 

This should be changed so that without a Gadget of Investigation you cannot differentiate between a glass of Berry Juice and a glass of Poisoned Berry Juice, and also that tomato juice and blood are obviously two different things. 

 drink/poisonberryjuice
   name = "Poison Berry Juice"
   id = "poisonberryjuice"
   description = "Poison berry juice is a fruity and ironically very tasty beverage made from a blend of different types of poisonous berries."
   color = "#863353" // rgb: 134, 51, 83

   glass_icon_state = "poisonberryjuice"
   glass_name = "glass of poison berry juice"
   glass_desc = "But it smells and looks so yummy..."

**Comment by Puckaboo2** [comment]
Poisoned berry juice is darker and more thick, rgb wise, as poisoned berries are more dark. However, by taste and smell, it's difficult to identify the difference because they try to mimic actual berries. I can possible make poisoned berries and regular berries have the same sprite or something. I'm not sure what everyone's consensus is on this.

**Comment by Davnik** [comment]
So, when someone knows they have poison berry juice, they'll see the real description, but when it's poured into a glass, it seems identical to berry juice? That's dandy. I wonder if a beaker classifies as a glass.

Will close this issue when it enters the code. If it hasn't already. Puck ping

**Comment by Davnik** [comment]
Confirming this has been changed. I will note, the "glass of tomato juice" joke was classic, and tomato juice is more salty and delicious than bland, but these are issues for another time.
