### ISSUE TITLE
Straitjacket ??Bug??

### ISSUE THREAD

**Issue by Davnik** [HeavensGate/Eternal#312]
Apparently when you put a straitjacket on yourself, it dupes, into one on the ground? Various bug potential, someone who's witnessed this can comment with more details.

**Comment by Mewchild** [comment]
When equipping a straight jacket (sp, it's how it is on the server) onto yourself, it doesn't enter your contents. It instead goes into the worn_suit var. It doesn't show up on your inventory, but it DOES show up on your sprite, and all the effects persist. It can't be removed by any method, to include admin verbs, as drop_everything doesn't hit things outside contents.

**Comment by aztectornado** [comment]
It's almost like it's restraining you before it's put on. I don't know where to BEGIN finding the issue for this one, but I'll get to the bottom of it. 

....Not like people need to or CAN put it on themselves IRL anyway.

**Comment by Puckaboo2** [comment]
"You can't put this on yourself."

**Comment by aztectornado** [comment]
Hah, Puck actually said what I just did in my test build. I have the fix, but it modifies one of the files she worked on in her latest pull, so I'll wait until after the merge
