### ISSUE TITLE
PDA Slot

### ISSUE THREAD

**Issue by woothie** [HeavensGate/Eternal#34]
Bring back the PDA slot. Look at codebases that have it already and reverse-engineer. Bonus points if you actually ask before you steal, even if you legally can.

**Comment by Puckaboo2** [comment]
If my new PDA are accepted into Github, I will have to resprite the PDA slot to match the new ones.

**Comment by aztectornado** [comment]
I'm gonna do this now.

**Comment by aztectornado** [comment]
done.
