### ISSUE TITLE
Ghetto Surgery on Operating Tables

### ISSUE THREAD

**Issue by Davnik** [HeavensGate/Eternal#346]
Should ghetto surgery have an increased %chance of success per attempt on an operating table? I vote yes; in that atmosphere, you can take more care and patience, and the table is implied to have instruments which assist you in the surgery. Discuss!

**Comment by Davnik** [comment]
Card Games on Motorcycles.

**Comment by KipperIalovskii** [comment]
I believe this is already implemented. Whether the patient is on a rollerbed, table, floor/etc., all affect the chances of botched surgery. At least, in the code I am used to.

No matter how careful you are, you're still using a glass shard, and the like, to slice someone open. That's the risk of ghetto surgery, and it should remain a dangerous procedure.

**Comment by Mewchild** [comment]
This is exactly how it works, as Kipp mentioned.

**Comment by Davnik** [comment]
Hehehe. Kipper looks like an ethernet port.
