### ISSUE TITLE
ERP discussion/disallowance

### ISSUE THREAD

**Issue by Mewchild** [HeavensGate/Eternal#373]
At the time of this writing, there are, on the server, a trio of individuals involved in what amounts to cuckolding one another in an ERP tryst. This seems to becoming a common theme, where people join for the express purpose of ERP, and retreat away from any and all forms of contact with other users. I propose that the rules be edited to disallow ERP.

**Comment by woothie** [comment]
Use your best judgement. Any admin essentially has full rights to do
whatever he or she deems valid to deal with a problem.

It does seem like the community isn't getting the whole "just play the game
too and don't get weird about it" gist, so if a vote were to be held, I'd
stand with you in just outright disallowing (explicit/excessively weird??)
ERP given our record.

If anything, the individual admin could look away if it's obviously an
alright scenario or whatever. Again, best judgement and common sense
overrules all rules. I'll make sure to put that in somewhere visible too.
