### ISSUE TITLE
Atmospherics strange issues

### ISSUE THREAD

**Issue by woothie** [HeavensGate/Eternal#50]
Pressurization and airlocks in general are acting really, really fucking wierd. For instance, we had a player experience 500 kPa in a solar airlock at some point, and in others the depressurizaton is crazy slow (0.5 kPa per second takes a while). We assume this is after Bay touched some ZAS or atmos code. Debug and find the issue, street cred en masse to those who can find it. Or kudos to those who can discredit this and tell me "no this is map issue wow.", whatever fixes it.

**Comment by woothie** [comment]
New map made the issue less of a murderthing, causing only slight issues with IC interpetation now. Still an issue regardless, abeit less urgent now.

**Comment by Davnik** [comment]
Bay has modified solars to open to exterior at a normal pace, and open to interior QUICKLY - immediately shooting to 105kPa and winding down to 101. As this seems to be how ours operates presently, I think this issue can be closed until it becomes a problem.

**Comment by woothie** [comment]
Uh, was fixed ages ago. Lalalalalalal-
