### ISSUE TITLE
OOC chat separation

### ISSUE THREAD

**Issue by woothie** [HeavensGate/Eternal#57]
Given the weird crashes we're having (not even crashes, it's byond using 100% of cpu and freezing), I'm considering having OOC chat being handled by a separate process/socket/some shit, to make people able to still talk/admins being able to notify players on what's going on and what will happen to fix it. I have absolutely no idea if this is even technically possible, but the idea stands.

**Comment by Davnik** [comment]
We're no longer having the crashes, and we're considering STUI in #155, so I question how useful this will continue to be.

**Comment by woothie** [comment]
Not very.
