### ISSUE TITLE
Bans not added to notes

### ISSUE THREAD

**Issue by woothie** [HeavensGate/Eternal#62]
This is a feature we'd like to see because it's dam useful, and why wouldn't it already do this!

**Comment by Jacquar** [comment]
My ban notes are automatically appearing, judging by a 1week temp ban I applied to a griefer earlier today. Is this issue fixed, should it be closed?

**Comment by woothie** [comment]
Issue #102 says it's still around.

**Comment by sshado** [comment]
Can I get more information on when this happens? Does it work for some bans and not others? Does it work for job bans? Temporary or permanent?

Can't sort it until I know which instances aren't working.

**Comment by Davnik** [comment]
Adminbot adds notes on Player Panel > Jobban, but not on Player Panel > Ban. Please have adminbot make notes of both.

**Comment by Davnik** [comment]
This seems to be resolved; reopen if not.
