### ISSUE TITLE
Science Deficiency

### ISSUE THREAD

**Issue by Jacquar** [HeavensGate/Eternal#71]
Not enough science.

ADD MORE.

I'm waiting.

In other words, sorry, I'm testing the issue posting system thing for the first time, sorry I'm late.

**Comment by Jacquar** [comment]
Gods damnit my shark is hungry, I NEED SCIENCE, NOW!

**Comment by Jacquar** [comment]
Excellent work, Jack. Keep up the good work, Woothie.

Damn we're good at this.

**Comment by woothie** [comment]
Yes.
Yes, we are.
