### ISSUE TITLE
Atmos visual bug

### ISSUE THREAD

**Issue by Pdactyl** [HeavensGate/Eternal#79]
After poking a couple of holes in the engine room for someone to emergency drain some accidentally released phoron, this happened: http://gyazo.com/fcb6ede2d36006eca02c8017b821b42b

There is no phoron detected with analyze air, and it does not ignite.

**Comment by Mewchild** [comment]
I've seen this happening very rarely, as of late. eg not within 3-4 weeks. The clear toxins/fire in zone is also a way to fix it, though god only knows how that works.

**Comment by Davnik** [comment]
spam it
pray "pls spess jeebus"
