### ISSUE TITLE
Engineering station lacks telecomms/radio

### ISSUE THREAD

**Issue by KryptonOsmium** [HeavensGate/Eternal#81]
There's a telecomms array at the engineering station (The one you use the shuttle to travel to) but for some reason radios don't work. You can also recieve but not send PDA messages there, so that might be an issue, too.

**Comment by woothie** [comment]
Interesting. I'll look at it when I have the time

**Comment by Davnik** [comment]
The Tcomms Relay there uses the Ruski preset, and never turns on. There's also only that one item; I have a feeling it needs some more tech and something to let it turn on. The plot thickens.

**Comment by woothie** [comment]
Note: Similar issues on the asteroid, although that's possibly just range limitations. TESTS!

**Comment by Davnik** [comment]
I believe this was fixed long ago. Will confirm with devs.
