### ISSUE TITLE
Arrivals Shuttle

### ISSUE THREAD

**Issue by Davnik** [HeavensGate/Eternal#88]
The latticing to the arrivals shuttle needs to be broken up a little, because it looks ech. If you want to go ahead and knock out another priority with this one, go ahead and move the Port Escape Pods down to the Arrivals Hallway, and make a skybridge (reference the Mining Outpost for inspiration) to the Docked Arrivals Shuttle. That can just knock out all the latticing, because it isn't precariously tethered, it's got a legitimate airlock to seal to. Ideally, the Arrivals Shuttle will serve as an alternate Escape Shuttle. And THAT is probably beyond trial devs.

**Comment by Jacquar** [comment]
In short, don't bother, we're remapping the entire arrivals shuttle thing.

**Comment by Jacquar** [comment]
This will be planned in detail, don't touch it for now. We'll be assigning it in time. We'll either do it solely via Skype or create a new ticket.
