### ISSUE TITLE
Ghostless Observers

### ISSUE THREAD

**Issue by Davnik** [HeavensGate/Eternal#97]
Observers cannot receive allow-player-to-respawn if they did not formerly ghost out of a mob. They need to be assigned a mob, so they can be allowed to respawn. Any attempt they make to return to body or similar reports that they have no body.

**Comment by Jacquar** [comment]
Easily fixed by an admin, so low-priority item.

**Comment by Davnik** [comment]
This may cause subsidiary issues, so that admin fix should be made common admin knowledge in the interim.

**Comment by woothie** [comment]
Fixed in #185
