### ISSUE TITLE
 Quit Kicking Yourself

### ISSUE THREAD

**Issue by Davnik** [HeavensGate/Eternal#98]
Mobs are apparently able to "land a strong kick against [their own] groin!" Which, sounds like a really neat trick! Try to make it so that only /fist mechanics can interact with yourself. Despite one's ability to really mess themselves up stepping on their own toes.

**Comment by Jacquar** [comment]
One minute people want ERP banned, then they're /fisting their groins.

**Comment by Davnik** [comment]
I never wanted ERP banned!
